### ISSUE TITLE
Idea : create a transform stream

### ISSUE THREAD

**Issue by rom1504** [AresRPG/aresrpg-map-colors#4]
https://nodejs.org/api/stream.html#stream_duplex_and_transform_streams

An idea would be to create a transform stream that would take as input pictures and would produce updates as map packets :
* Either a full packet update
* Either several smaller updates if not too many pixel changed compared to the last image
This could be achieved by storing internally in the stream the last map-format image.

This could be used to display a stream of image in a map :
* A video
* A streaming video : screencast (browser,...), Webcam,...

**Comment by Sceat** [comment]
Yup that's a good idea, i'm currently reworking the from image function to make less calculations and just map datas!
i'll work on streams right after

**Comment by Sceat** [comment]
> NOTE for newcomers : always refer to #5 to follow progression and ETA
